### ISSUE TITLE
Why is exchange.publish no coroutine?

### ISSUE THREAD

**Issue by georgwaechter** [benjamin-hodgson/asynqp#10]
Hi,

i'm wondering whether exchange.publish() is no coroutine? How works the asynchronous implementation  in this case?

Thanks in advance

Georg

**Comment by benjamin-hodgson** [comment]
It doesn't need to be a coroutine. [The specification](https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.publish) doesn't include any form of 'publish confirmation' (say, a `publish-ok` method), so there's no reason to wait around once we've sent the data up to the server. I believe AMQP was designed this was for performance reasons.

**Comment by georgwaechter** [comment]
Thank you for the fast response and the explanation!

Ok, I understand.  Previously I thought that all socket operations need to be asynchronous, even those that dont wait for an answer. This seems to be a bit different from nodejs, which I used before.

**Comment by benjamin-hodgson** [comment]
`asyncio` takes care of asynchronously flushing data to the socket for you. See [the docs](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.WriteTransport.write)
