### ISSUE TITLE
0.5.1 broken under 3.7; Fix already merged - needs release

### ISSUE THREAD

**Issue by pglombardo** [benjamin-hodgson/asynqp#108]
PR #104 (August) hasn't been released.  Version [0.5.1](https://github.com/benjamin-hodgson/asynqp/releases) (June) still breaks under Python 3.7

Can we put together a 0.5.2 release please?

Thanks

**Comment by benjamin-hodgson** [comment]
https://pypi.org/project/asynqp/0.6/
