### ISSUE TITLE
Ability to pass attributes to declare_queue

### ISSUE THREAD

**Issue by ralphje** [benjamin-hodgson/asynqp#2]
Some extensions require additional arguments for a queue, e.g. message TTL and dead lettering. See for instance https://www.rabbitmq.com/ttl.html. However, `Channel.queue_declare` does not provide any mechanism to pass these attributes to the underlying `spec.QueueDeclare` 

From `ChannelMethodSender` it seems that there's the ability to also pass attributes to `ExchangeDeclare`, `QueueBind`, `QueueUnbind` and `BasicConsume`. Perhaps these dicts should be exposed too.

(There are more specialized arguments that have set defaults in `ChannelMethodSender`. If possible, these may or may not be useful to expose.)

**Comment by benjamin-hodgson** [comment]
Closed by #27
