### ISSUE TITLE
No exception when failing to create a queue

### ISSUE THREAD

**Issue by therve** [benjamin-hodgson/asynqp#22]
If I try to redeclare a queue with different parameters, rabbit fails with a PRECONDITION_FAILED, but the error is not propagated to the queue_declare call, leaving the code hanging forever.

I'm not sure exactly how to fix this, but it seems that handle_ChannelClose would need to call something along the lines of notify_connection_closed. Ideally it would contain the reply text to have a meaningful exception.

**Comment by benjamin-hodgson** [comment]
Thanks for the bug report! Sorry I haven't been able to respond sooner, I've been on holiday :sunglasses: 

I think this should be reasonably easy to fix, thanks to @lenzenmi 's hard work building an error-handling framework in #19 . I think I will have time to have a proper look on Tuesday.

In the mean-time, could you send me a full example of some code which reproduces the issue?

**Comment by benjamin-hodgson** [comment]
I've fixed the issue with _no_ exception being raised; I've opened another one to deal with error messages, see #23.

Could you try taking the latest master for a spin to see if it solves your problem?

**Comment by therve** [comment]
Thanks, it does raise an exception now.

For the record, my example looked like this, with myqueue being a non-durable queue:


import asyncio
import asynqp

@asyncio.coroutine
def send_and_receive():
    connection = yield from asynqp.connect('localhost', 5672, username='guest', password='guest')

    channel = yield from connection.open_channel()

    queue = yield from channel.declare_queue('myqueue')

    def consumer(message):
        print(message.json())

    consumer = yield from queue.consume(consumer)



if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(send_and_receive())
    loop.run_forever()
