### ISSUE TITLE
connection_lost should not raise exception when called with None

### ISSUE THREAD

**Issue by urbaniak** [benjamin-hodgson/asynqp#31]
connection_lost is called each time the connection is closing, even with .close() method (according to https://docs.python.org/3/library/asyncio-protocol.html):
> close(self)
> Close the transport. If the transport has a buffer for outgoing data, buffered data will be flushed asynchronously. No more data will be received. After all buffered data is flushed, the protocol’s connection_lost() method will be called with None as its argument.

For reconnecting purposes there should be other way, without raising an exception on event loop (which in our cases is running multiple things, not just asynqp).

**Comment by benjamin-hodgson** [comment]
Thanks for getting in touch.

Here's what the current implementation does:

```python
    def connection_lost(self, exc):
        self._send_connection_closed_poison_pill()
        if exc is None:
            raise ConnectionClosedError('The connection was closed')
        else:
            raise ConnectionLostError('The connection was unexpectedly lost') from exc
```

Are you proposing changing this to something like the following?

```python
    def connection_lost(self, exc):
        self._send_connection_closed_poison_pill()
        if exc is None:
            return
        else:
            raise ConnectionLostError('The connection was unexpectedly lost') from exc
```

**Comment by urbaniak** [comment]
yeah, it can be even simpler:

        if exc is not None:
            raise ConnectionLostError('The connection was unexpectedly lost') from exc

**Comment by benjamin-hodgson** [comment]
Makes sense, it's not an exceptional case. :+1: I'm trying to figure out whether clients have any way to detect whether the server has closed the connection which doesn't involve catching an exception. I'm going to leave this issue open until we have a compelling API for that.

**Comment by benjamin-hodgson** [comment]
Done and done.

**Comment by urbaniak** [comment]
:+1: cool, thanks! ;)
