### ISSUE TITLE
NotImplementedError when passing NoneType value to the buffer

### ISSUE THREAD

**Issue by renatomassaro** [benjamin-hodgson/asynqp#32]
Hello,

When passing a dict that contains one or more `None` values I get a `NotImplementedError` raised on `serialization.py`, line 280-ish, function `pack_field_value`.

Now I'm not sure if I am doing something wrong by passing a None value, but I think the lib should convert it to a null value.

The quick-fix I did was set value as False, which is not the same but works for me. I guess the correct way would be to add something like:

```python
# ...
elif value is None:
    buffer += b'V' 
    buffer += pack_null(value)
# ...
```

However, I don't know how to implement that with the struct lib you are using. Any ideas?

**Edit:** Reading https://www.rabbitmq.com/resources/specs/amqp0-9-1.pdf, page 31, looks like None should be sent as `void (V)`. There already is a `_read_void()`, but no `pack_void()`. Furthermore, looks like struct implementation for void (`P`) isn't available with network/big-endian ordering (`!`). I tried packing it as False with the b'V' flag but it didn't work.

**Comment by renatomassaro** [comment]
Got the same error for a Float type, now this one was easier to implement with `f` flags for both AMQP and Struct.

**Comment by benjamin-hodgson** [comment]
Thanks for the bug report. Could you provide a snippet of code which reproduces the issue and the stack trace and error message?

**Comment by renatomassaro** [comment]
Sorry, I forgot to say it's a dict passed on the `headers` arg.
Here it goes:
```
import asyncio
import asynqp

@asyncio.coroutine
def hello_world():

    connection = yield from asynqp.connect('rabbitmq.service.consul',
                                           5672,
                                           username='he2',
                                           password='he2')

    channel = yield from connection.open_channel()

    exchange = yield from channel.declare_exchange('test.exchange', 'direct')
    queue = yield from channel.declare_queue('test.queue')

    yield from queue.bind(exchange, 'routing.key')

    msg = asynqp.Message(
        {'hello': 'world'},
        headers={'badval1': None, 'badval2': 1.0}
    )
    exchange.publish(msg, 'routing.key')

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(hello_world())
```

And the stack trace:

    # Stack Trace:
    # Traceback (most recent call last):
    #   File "/etc/he2/sandbox.py", line 59, in <module>
    #     loop.run_until_complete(hello_world())
    #   File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    #     return future.result()
    #   File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    #     raise self._exception
    #   File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    #     result = next(coro)
    #   File "/etc/he2/sandbox.py", line 23, in hello_world
    #     exchange.publish(msg, 'routing.key')
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/exchange.py", line 42, in publish
    #     self.sender.send_BasicPublish(self.name, routing_key, mandatory, message)
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/channel.py", line 361, in send_BasicPublish
    #     self.send_content(message)
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/channel.py", line 390, in send_content
    #     self.protocol.send_frame(header_frame)
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/protocol.py", line 42, in send_frame
    #     self.transport.write(frame.serialise())
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/frames.py", line 34, in serialise
    #     self.payload.write(bytesio)
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/message.py", line 195, in write
    #     val.write(bytesio)
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/amqptypes.py", line 181, in write
    #     stream.write(serialisation.pack_table(self))
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/serialisation.py", line 283, in pack_table
    #     buffer += pack_field_value(value)
    #   File "/usr/local/lib/python3.4/dist-packages/asynqp/serialisation.py", line 273, in pack_field_value
    #     raise NotImplementedError()
    # NotImplementedError

If you can confirm this is a bug I have the solution for float packing ready and I can PR it. No idea how to fix for `None`, though.

**Comment by benjamin-hodgson** [comment]
Thanks for getting back to me! Yeah, it definitely looks like a bug. I'd be happy to accept a pull request; I'll try to find time to look into the other issue this week (or possibly next week)
