### ISSUE TITLE
Provide API to "wait until message arrive and get it"

### ISSUE THREAD

**Issue by socketpair** [benjamin-hodgson/asynqp#38]
`Consumer` pattern is not good in asyncio. Since it is callback-based. Callback-based apps are proven to be bad. What happen if exception raised in `Consumer.callback()`?

I want to use this pattern:

```
@asyncio.coroutine
def some_fun():
    channel = yield from connection.open_channel()
    exchange = yield from channel.declare_exchange('xxx', 'direct')
    queue = yield from channel.declare_queue('yyyy')
    yield from queue.bind(exchange, 'zzz')
    while True:
        msg = yield from queue.wait_and_get() # function name just for example
        try:
            ...
        except Exception:
            msg.reject()
        else:
            msg.ack()
```

This pattern gives me full control over process of receiving/handling messages. Even with timeouts if I want. Current API of `queue.Get()` returns immediatelly if there are no messages in queue, so I cannot wait for a message.

**Comment by benjamin-hodgson** [comment]
Use a [`Queue`](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue).

```python
# ...
queue = yield from channel.declare_queue('abc')
q = asyncio.Queue()
yield from queue.consume(q.put_nowait)
msg = yield from q.get()
```
