### ISSUE TITLE
Why callback in consume can't be coroutine?

### ISSUE THREAD

**Issue by purpleP** [benjamin-hodgson/asynqp#85]
This defiles all benefits of using this library.

I can't understand how this library works entirely, but It seems that you using callbacks to deliver messages. Why?

Shouldn't the code conceptually be something like a bit while True loop in which you're waiting for something from server, then when it's available you dispatch it to another coroutines?

**Comment by farefernandez** [comment]
@purpleP I stumbled upon the very same thing in #84

**Comment by purpleP** [comment]
@farefernandez Wow, thanks. I've tried using create_task from a callback, but it didn't worked for some reason giving me something like 'Can't create tasks when loop is running'. But now it seems to be working.

**Comment by purpleP** [comment]
I'll close the issue if everything will be alright.
