### ISSUE TITLE
 Queue get as a blocking method

### ISSUE THREAD

**Issue by Ledokol** [benjamin-hodgson/asynqp#89]
Why `get()` method returns `None`  if there were no messages on the queue instead of wait them?

**Comment by Drizzt1991** [comment]
Because it implements the `sync` API for queue polling. It's part of AMQP spec, see https://www.rabbitmq.com/amqp-0-9-1-reference.html#basic.get
You can use the `queue.consume` to register a callback for messages and use it to get somehow an API like you want:
```python
from asyncio import Queue

async def process_asynqp_queue(asynqp_queue):
     msg_buffer = Queue()
     asynqp_queue.consume(msg_buffer.put_nowait)
     while True:
         msg = await msg_buffer.get()

```

**Comment by Drizzt1991** [comment]
Of course a proper implementation with all error handling on reconnects is more troublesome thou...
