### ISSUE TITLE
Provide support to send message directly to queue bypassing exchange

### ISSUE THREAD

**Issue by horpto** [benjamin-hodgson/asynqp#90]
Now I can publish message only over exchange, but some libraries (for example, https://www.npmjs.com/package/amqplib for Nodejs) can pass exchange (which can be fanout or topic) and send directly to known queue.

**Comment by benjamin-hodgson** [comment]
You can do that using [the default exchange](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-default).
